spring:
  config:
    activate:
      on-profile: test

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: health, info, loggers, shutdown, prometheus
  endpoint:
    health:
      exposure:
        include: health, info, loggers, shutdown, prometheus
      show-components: always
      show-details: always

logging:
  level:
    dev.changui.jpa.interceptor: trace
