spring:
  profiles:
    active: test
---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:mysql://172.17.0.1:3306/demo_jpa_schema
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:mysql://172.17.0.1:3306/demo_jpa_schema
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
